# Generated by Django 2.0.7 on 2019-11-10 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('parent_code', models.CharField(blank=True, max_length=6)),
                ('leadtime', models.IntegerField()),
                ('consumption', models.IntegerField()),
                ('bom_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4)),
                ('manager', models.CharField(blank=True, max_length=10)),
                ('info', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FlowOfProduction',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('required_time', models.IntegerField(default=10)),
                ('note', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=2)),
                ('specification', models.CharField(max_length=10)),
                ('Quota', models.IntegerField(blank=True)),
                ('safety_stock_quantity', models.IntegerField(blank=True)),
                ('is_buy', models.BooleanField(default=True)),
                ('item', models.CharField(default='物料', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next0', to='erp_1.ProductionChain')),
                ('pre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre0', to='erp_1.ProductionChain')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionProcess',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('required_time', models.IntegerField()),
                ('note', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=6)),
                ('user', models.ManyToManyField(related_name='user_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('on_the_job', models.BooleanField()),
                ('qualification', models.CharField(blank=True, max_length=10)),
                ('native_place', models.CharField(blank=True, max_length=20)),
                ('post', models.CharField(blank=True, max_length=10)),
                ('level', models.CharField(blank=True, max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('nation', models.CharField(blank=True, max_length=5)),
                ('seniority', models.IntegerField(blank=True)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_1.Department')),
            ],
        ),
        migrations.AddField(
            model_name='productionprocess',
            name='leading_man',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_1.Staff'),
        ),
        migrations.AddField(
            model_name='productionprocess',
            name='materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_1.Materials'),
        ),
        migrations.AddField(
            model_name='productionchain',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_1.ProductionProcess'),
        ),
        migrations.AddField(
            model_name='flowofproduction',
            name='leading_man',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_1.Staff'),
        ),
        migrations.AddField(
            model_name='flowofproduction',
            name='productionChain',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chain', to='erp_1.ProductionChain'),
        ),
        migrations.AddField(
            model_name='bom',
            name='materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_1.Materials'),
        ),
    ]
