# Generated by Django 2.0.7 on 2019-11-10 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('supplier', models.CharField(blank=True, max_length=10)),
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('applicant', models.CharField(blank=True, max_length=10)),
                ('department', models.CharField(blank=True, max_length=4)),
                ('send_time', models.DateField(blank=True)),
                ('material_id', models.CharField(max_length=6)),
                ('material_name', models.CharField(blank=True, max_length=10)),
                ('specifications', models.CharField(blank=True, max_length=10)),
                ('amount', models.IntegerField(blank=True)),
                ('required_time', models.DateField(blank=True, max_length=10)),
                ('state', models.CharField(default='未处理', max_length=3)),
                ('remarks', models.CharField(blank=True, max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('tran_price', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('send_time', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=20)),
                ('order_maker', models.CharField(blank=True, max_length=10)),
                ('reviewer', models.CharField(blank=True, max_length=10)),
                ('predict_time', models.DateField(blank=True)),
                ('remarks', models.CharField(blank=True, max_length=100)),
                ('reality_time', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, default='未确认', max_length=3)),
                ('trouble_order', models.BooleanField(default=0)),
                ('credit_mark', models.FloatField(blank=True, null=True)),
                ('quality_mark', models.FloatField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=10)),
                ('assess_time', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_1.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('contact', models.CharField(blank=True, max_length=10)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('mail', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True)),
                ('tran_price', models.FloatField(blank=True)),
                ('rate', models.FloatField(blank=True)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_1.Materials')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_5.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_5.Supplier'),
        ),
        migrations.AddField(
            model_name='detail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_5.Order'),
        ),
    ]
