# Generated by Django 2.0.7 on 2019-11-10 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp_1', '0001_initial'),
        ('erp_5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('app_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('io', models.CharField(blank=True, max_length=1)),
                ('goods_id', models.CharField(blank=True, max_length=6)),
                ('goods_name', models.CharField(blank=True, max_length=10)),
                ('norms', models.CharField(blank=True, max_length=10)),
                ('demand', models.IntegerField(blank=True)),
                ('demand_io', models.IntegerField(blank=True, default=0)),
                ('unit', models.CharField(blank=True, max_length=5)),
                ('date_app', models.DateField()),
                ('date_io', models.DateField(blank=True)),
                ('state', models.CharField(blank=True, max_length=6)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant', to='erp_1.Staff', verbose_name='申请人')),
                ('charger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charger', to='erp_1.Staff', verbose_name='管理员')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_5.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('app_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('WMS_id', models.CharField(blank=True, max_length=2)),
                ('location', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.CharField(default=0, max_length=14, primary_key=True, serialize=False)),
                ('goods_id', models.CharField(blank=True, max_length=6)),
                ('goods_name', models.CharField(blank=True, max_length=10)),
                ('norms', models.CharField(blank=True, max_length=10)),
                ('characteristic', models.CharField(blank=True, max_length=10)),
                ('value', models.CharField(blank=True, max_length=1)),
                ('order_point', models.CharField(blank=True, max_length=6)),
                ('date', models.DateField(auto_now=True)),
                ('pur', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(blank=True, max_length=6)),
                ('stock_now', models.IntegerField()),
                ('stock_way', models.IntegerField()),
                ('stock_secure', models.IntegerField()),
                ('stock_real', models.IntegerField()),
                ('stock_free', models.IntegerField()),
                ('unit', models.CharField(blank=True, max_length=5)),
                ('charger_id', models.CharField(blank=True, max_length=6)),
                ('charger_name', models.CharField(blank=True, max_length=10)),
                ('button', models.CharField(default='采购申请', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.CharField(default=0, max_length=6, primary_key=True, serialize=False)),
                ('goods_id', models.CharField(blank=True, max_length=6)),
                ('goods_name', models.CharField(blank=True, max_length=10)),
                ('norms', models.CharField(blank=True, max_length=10)),
                ('WMS_id', models.CharField(blank=True, max_length=2)),
                ('location', models.CharField(blank=True, max_length=10)),
                ('amount_app', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=5)),
                ('date_in', models.DateField(blank=True)),
                ('time', models.CharField(blank=True, max_length=5)),
                ('date_line', models.DateField(blank=True)),
                ('charger_id', models.CharField(blank=True, max_length=6)),
                ('charger_name', models.CharField(blank=True, max_length=10)),
                ('deal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('goods_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('goods_name', models.CharField(blank=True, max_length=10)),
                ('WMS_out_id', models.CharField(blank=True, max_length=2)),
                ('out_location', models.CharField(blank=True, max_length=10)),
                ('WMS_in_id', models.CharField(blank=True, max_length=2)),
                ('in_location', models.CharField(blank=True, max_length=10)),
                ('charger_out_id', models.CharField(blank=True, max_length=6)),
                ('charger_out_name', models.CharField(blank=True, max_length=10)),
                ('charger_in_id', models.CharField(blank=True, max_length=6)),
                ('charger_in_name', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WMS',
            fields=[
                ('WMS_id', models.CharField(blank=True, max_length=2)),
                ('location', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('goods_id', models.CharField(blank=True, max_length=6)),
                ('goods_name', models.CharField(blank=True, max_length=10)),
                ('norms', models.CharField(blank=True, max_length=10)),
                ('volume', models.IntegerField(default=10000)),
                ('employ', models.IntegerField(default=0)),
                ('ratio', models.FloatField(default=0)),
                ('charger_id', models.CharField(blank=True, max_length=6)),
                ('charger_name', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
